cuda: true
batch_size: 1
num_workers: 0
visualization:
  active: true
  separate_img: false
  split_in_out: false
  img_out:

visualize: true
input: "/media/alex/Datasets/04_animal-clean/evaluation/chimp/input_data"
output: "/media/alex/Datasets/04_animal-clean/evaluation/chimp/output_orca-mask"
maintain_directory_structure: true
file_ext:
model_path: "/media/alex/Datasets/model_storage/ANIMAL-CLEAN/chimp/chimpanzee-H_0-M_100-FNCJ_last.ckpt"
sequence_length: 1.28
