cuda: true
batch_size: 1
num_workers: 0
visualization:
  active: true
  separate_img: false
  split_in_out: false
  img_out:

visualize: true
input: "/media/alex/Datasets/04_animal-clean/evaluation/bat/input_data"
output: "/media/alex/Datasets/04_animal-clean/evaluation/bat/output"
maintain_directory_structure: true
file_ext:
model_path: "/media/alex/Datasets/model_storage/ANIMAL-CLEAN/bat/bat-H50-3_v22.ckpt"
sequence_length: 1.28
